### ISSUE TITLE
Jetson Nano - Illegal Instruction

### ISSUE THREAD

**Issue by mitchross** [tomshaffner/PiThermalCam#4]
Im using a Jetson Nano and trying to get this thermal camera setup to work. Good news is that I'm getting sensor data per this step. 

When testing the IMX thermal camera on the nano I can get to this step and get printed data... 
![image](https://user-images.githubusercontent.com/6330506/120417569-0c2aac80-c32d-11eb-87e2-46de10911f19.png)

However, 

When I try to import pithermal cam on a jetson nano I get this error.
>>> import pithermalcam
Illegal instruction (core dumped)

Same error occurs starting the web server. so I figured id narrow it down to the lowest common denominator in the import and see which library is causing the issue. 

Is there some way to debug this further?

**Comment by mitchross** [comment]
Got passed this issue with adding "export OPENBLAS_CORETYPE=ARMV8" to bash rc

Now I see

```
 python3 web_server.py
Traceback (most recent call last):
  File "web_server.py", line 153, in <module>
    start_server()
  File "web_server.py", line 134, in start_server
    thermcam = pithermalcam(output_folder=output_folder)
  File "/home/vanillax/.local/lib/python3.6/site-packages/pithermalcam/pi_therm_cam.py", line 47, in __init__
    self.update_image_frame()
  File "/home/vanillax/.local/lib/python3.6/site-packages/pithermalcam/pi_therm_cam.py", line 223, in update_image_frame
    self._pull_raw_image()
  File "/home/vanillax/.local/lib/python3.6/site-packages/pithermalcam/pi_therm_cam.py", line 85, in _pull_raw_image
    self.mlx.getFrame(self._raw_image) # read mlx90640
  File "/usr/local/lib/python3.6/dist-packages/adafruit_mlx90640.py", line 126, in getFrame
    status = self._GetFrameData(mlx90640Frame)
  File "/usr/local/lib/python3.6/dist-packages/adafruit_mlx90640.py", line 155, in _GetFrameData
    raise RuntimeError("Too many retries")
RuntimeError: Too many retries
Exiting...
Cleaning up pins
```

**Comment by mitchross** [comment]
Running this code works tho
```

##################################
# MLX90640 Test with Raspberry Pi
##################################
#
import time,board,busio
import numpy as np
import adafruit_mlx90640

i2c = busio.I2C(board.SCL, board.SDA, frequency=400000) # setup I2C
mlx = adafruit_mlx90640.MLX90640(i2c) # begin MLX90640 with I2C comm
mlx.refresh_rate = adafruit_mlx90640.RefreshRate.REFRESH_2_HZ # set refresh rate

frame = np.zeros((24*32,)) # setup array for storing all 768 temperatures
while True:
    try:
        mlx.getFrame(frame) # read MLX temperatures into frame var
        break
    except ValueError:
        continue # if error, just read again

# print out the average temperature from the MLX90640
print('Average MLX90640 Temperature: {0:2.1f}C ({1:2.1f}F)'.\
      format(np.mean(frame),(((9.0/5.0)*np.mean(frame))+32.0)))
```

 python3 test.py

Average MLX90640 Temperature: 26.7C (80.1F)
Exiting...
Cleaning up pins

**Comment by tomshaffner** [comment]
Hi Mitch,

I don't believe this is actually an issue with the library. Maybe open a discussion about it?

I haven't worked with the device you're referencing though so unfortunately can't support. Best of luck on it though!

**Comment by Grountex** [comment]
Receiving 
126, in getFrame
    status = self._GetFrameData(mlx90640Frame)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_mlx90640.py", line 155, in _GetFrameData
    raise RuntimeError("Too many retries")
RuntimeError: Too many retries

too
